### ISSUE TITLE
amd64 for linux missing on the release

### ISSUE THREAD

**Issue by dragon040** [YaleUniversity/packer-plugin-goss#85]
Some how I am not able to see the release "packer-plugin-goss_v3.2.9_x5.0_linux_amd64.zip" on the list.

**Comment by FalcoSuessgott** [comment]
Yeah linux_amd64 is excluded in goreleaser, as recommended in hashicorps scaffolding template (https://github.com/hashicorp/packer-plugin-scaffolding/blob/bf869f2cc3ebfd3b520ddad5fb63f66144810fe0/.goreleaser.yml#L53). I cant really tell you how but it should nevertheless work for linux_amd64 systems as I have used it successfully locally and during CI.. did u give it a try?

**Comment by FalcoSuessgott** [comment]
until #86 is merged u should be able to use `v3.2.8`
