### ISSUE TITLE
Add quiet tags to curl and wget

### ISSUE THREAD

**Issue by wazoo** [YaleUniversity/packer-plugin-goss#95]
This is a feature request to add `--quiet` to wget and `--silent` on curl at [this point in the code](https://github.com/YaleUniversity/packer-plugin-goss/blob/master/provisioner/goss/packer-provisioner-goss.go#L333) to cause them to not output download statistics.  

When using this plugin the output from curl shows up as red in a packer build (because the output is from stderr).  

Example:

![image](https://github.com/YaleUniversity/packer-plugin-goss/assets/216878/013790f7-1bc6-4890-809d-58586f1e096d)

This isn't a functional problem but it would be less confusing for users that are looking for red text meaning error in CI job logs.  .

**Comment by FalcoSuessgott** [comment]
this is available in `v3.2.12`, you might wanna give it a try and report back
